// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace AmaFon.CrowdAct.Net.DataLayer.Entities
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    // ActivityLanguage
    /// <summary>
    /// Defines the <see cref="ActivityLanguage" />
    /// </summary>
    [Table("ActivityLanguage", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class ActivityLanguage
    {
        /// <summary>
        /// Gets or sets the ActivityId
        /// ActivityID (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"ActivityID", Order = 1, TypeName = "int")]
        [Index(@"PK_ActivityLanguage", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Activity ID")]
        public int ActivityId { get; set; }

        /// <summary>
        /// Gets or sets the LanguageId
        /// LanguageID (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"LanguageID", Order = 2, TypeName = "int")]
        [Index(@"IX_ActivityLanguage_LanguageID", 1, IsUnique = false, IsClustered = false)]
        [Index(@"PK_ActivityLanguage", 2, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Language ID")]
        public int LanguageId { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether Main
        /// </summary>
        [Column(@"Main", Order = 3, TypeName = "bit")]
        [Required]
        [Display(Name = "Main")]
        public bool Main { get; set; }

        // Foreign keys

        /// <summary>
        /// Gets or sets the Activity
        /// Parent Activity pointed by [ActivityLanguage].([ActivityId]) (FK_ActivityLanguage_Activity_ActivityID)
        /// </summary>
        [ForeignKey("ActivityId"), Required]
        public virtual Activity Activity { get; set; }

        /// <summary>
        /// Gets or sets the Language
        /// Parent Language pointed by [ActivityLanguage].([LanguageId]) (FK_ActivityLanguage_Language_LanguageID)
        /// </summary>
        [ForeignKey("LanguageId"), Required]
        public virtual Language Language { get; set; }
    }
}
// </auto-generated>