// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Amaris.Foundation.CrowdAct.NetDal.Entities
{

    // Activity
    [Table("Activity", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Activity
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK_Activity", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // ID (Primary key)

        [Column(@"Name", Order = 2, TypeName = "nvarchar(max)")]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name

        [Column(@"Description", Order = 3, TypeName = "nvarchar(max)")]
        [Display(Name = "Description")]
        public string Description { get; set; } // Description

        [Column(@"Picture", Order = 4, TypeName = "nvarchar(max)")]
        [Display(Name = "Picture")]
        public string Picture { get; set; } // Picture

        [Column(@"MaxParticipantNb", Order = 5, TypeName = "int")]
        [Required]
        [Display(Name = "Max participant nb")]
        public int MaxParticipantNb { get; set; } // MaxParticipantNb

        [Column(@"StartingDate", Order = 6, TypeName = "datetime2")]
        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Starting date")]
        public System.DateTime StartingDate { get; set; } // StartingDate

        [Column(@"EndingDate", Order = 7, TypeName = "datetime2")]
        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Ending date")]
        public System.DateTime EndingDate { get; set; } // EndingDate

        [Column(@"AddressID", Order = 8, TypeName = "int")]
        [Index(@"IX_Activity_AddressID", 1, IsUnique = true, IsClustered = false)]
        [Display(Name = "Address ID")]
        public int? AddressId { get; set; } // AddressID

        [Column(@"CharityID", Order = 9, TypeName = "int")]
        [Index(@"IX_Activity_CharityID", 1, IsUnique = false, IsClustered = false)]
        [Required]
        [Display(Name = "Charity ID")]
        public int CharityId { get; set; } // CharityID

        [Column(@"FieldID", Order = 10, TypeName = "int")]
        [Index(@"IX_Activity_FieldID", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Field ID")]
        public int? FieldId { get; set; } // FieldID

        [Column(@"TypeID", Order = 11, TypeName = "int")]
        [Index(@"IX_Activity_TypeID", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Type ID")]
        public int? TypeId { get; set; } // TypeID

        // Reverse navigation

        /// <summary>
        /// Child ActivityLanguages where [ActivityLanguage].[ActivityID] point to this entity (FK_ActivityLanguage_Activity_ActivityID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ActivityLanguage> ActivityLanguages { get; set; } // ActivityLanguage.FK_ActivityLanguage_Activity_ActivityID
        /// <summary>
        /// Child ActivityParticipants where [ActivityParticipant].[ActivityID] point to this entity (FK_ActivityParticipant_Activity_ActivityID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ActivityParticipant> ActivityParticipants { get; set; } // ActivityParticipant.FK_ActivityParticipant_Activity_ActivityID
        /// <summary>
        /// Child Requirements where [Requirement].[ActivityID] point to this entity (FK_Requirement_Activity_ActivityID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Requirement> Requirements { get; set; } // Requirement.FK_Requirement_Activity_ActivityID
        /// <summary>
        /// Child Skills (Many-to-Many) mapped by table [ActivitySkill]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Skill> Skills { get; set; } // Many to many mapping

        // Foreign keys

        /// <summary>
        /// Parent Address pointed by [Activity].([AddressId]) (FK_Activity_Address_AddressID)
        /// </summary>
        [ForeignKey("AddressId")] public virtual Address Address { get; set; } // FK_Activity_Address_AddressID

        /// <summary>
        /// Parent Charity pointed by [Activity].([CharityId]) (FK_Activity_Charity_CharityID)
        /// </summary>
        [ForeignKey("CharityId"), Required] public virtual Charity Charity { get; set; } // FK_Activity_Charity_CharityID

        /// <summary>
        /// Parent Category pointed by [Activity].([FieldId]) (FK_Activity_Category_FieldID)
        /// </summary>
        [ForeignKey("FieldId")] public virtual Category Category { get; set; } // FK_Activity_Category_FieldID

        /// <summary>
        /// Parent Type pointed by [Activity].([TypeId]) (FK_Activity_Type_TypeID)
        /// </summary>
        [ForeignKey("TypeId")] public virtual Type Type { get; set; } // FK_Activity_Type_TypeID

        public Activity()
        {
            ActivityLanguages = new System.Collections.Generic.List<ActivityLanguage>();
            ActivityParticipants = new System.Collections.Generic.List<ActivityParticipant>();
            Requirements = new System.Collections.Generic.List<Requirement>();
            Skills = new System.Collections.Generic.List<Skill>();
        }
    }

}
// </auto-generated>
