// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Amaris.Foundation.CrowdAct.NetDal.Entities
{

    // ActivityParticipant
    [Table("ActivityParticipant", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class ActivityParticipant
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"ActivityID", Order = 1, TypeName = "int")]
        [Index(@"PK_ActivityParticipant", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Activity ID")]
        public int ActivityId { get; set; } // ActivityID (Primary key)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"ParticipantID", Order = 2, TypeName = "int")]
        [Index(@"IX_ActivityParticipant_ParticipantID", 1, IsUnique = false, IsClustered = false)]
        [Index(@"PK_ActivityParticipant", 2, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Participant ID")]
        public int ParticipantId { get; set; } // ParticipantID (Primary key)

        [Column(@"ParticipantStatusID", Order = 3, TypeName = "int")]
        [Index(@"IX_ActivityParticipant_ParticipantStatusID", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Participant status ID")]
        public int? ParticipantStatusId { get; set; } // ParticipantStatusID

        // Foreign keys

        /// <summary>
        /// Parent Activity pointed by [ActivityParticipant].([ActivityId]) (FK_ActivityParticipant_Activity_ActivityID)
        /// </summary>
        [ForeignKey("ActivityId"), Required] public virtual Activity Activity { get; set; } // FK_ActivityParticipant_Activity_ActivityID

        /// <summary>
        /// Parent User pointed by [ActivityParticipant].([ParticipantId]) (FK_ActivityParticipant_User_ParticipantID)
        /// </summary>
        [ForeignKey("ParticipantId"), Required] public virtual User User { get; set; } // FK_ActivityParticipant_User_ParticipantID

        /// <summary>
        /// Parent ParticipantStatu pointed by [ActivityParticipant].([ParticipantStatusId]) (FK_ActivityParticipant_ParticipantStatus_ParticipantStatusID)
        /// </summary>
        [ForeignKey("ParticipantStatusId")] public virtual ParticipantStatu ParticipantStatu { get; set; } // FK_ActivityParticipant_ParticipantStatus_ParticipantStatusID
    }

}
// </auto-generated>
