// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace AmaFon.CrowdAct.Net.DataLayer.Entities
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    // City
    /// <summary>
    /// Defines the <see cref="City" />
    /// </summary>
    [Table("City", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class City
    {
        /// <summary>
        /// Gets or sets the Id
        /// ID (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK_City", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the Label
        /// Label (length: 450)
        /// </summary>
        [Column(@"Label", Order = 2, TypeName = "nvarchar")]
        [Index(@"AK_City_Label", 1, IsUnique = true, IsClustered = false)]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(450)]
        [StringLength(450)]
        [Display(Name = "Label")]
        public string Label { get; set; }

        /// <summary>
        /// Gets or sets the CountryId
        /// </summary>
        [Column(@"CountryID", Order = 3, TypeName = "int")]
        [Index(@"IX_City_CountryID", 1, IsUnique = false, IsClustered = false)]
        [Required]
        [Display(Name = "Country ID")]
        public int CountryId { get; set; }

        // Reverse navigation

        /// <summary>
        /// Gets or sets the Addresses
        /// Child Addresses where [Address].[CityID] point to this entity (FK_Address_City_CityID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Address> Addresses { get; set; }

        // Foreign keys

        /// <summary>
        /// Gets or sets the Country
        /// Parent Country pointed by [City].([CountryId]) (FK_City_Country_CountryID)
        /// </summary>
        [ForeignKey("CountryId"), Required]
        public virtual Country Country { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="City"/> class.
        /// </summary>
        public City()
        {
            Addresses = new System.Collections.Generic.List<Address>();
        }
    }
}
// </auto-generated>