// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Amaris.Foundation.CrowdAct.NetDal.Entities
{

    // Language
    [Table("Language", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Language
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ID", Order = 1, TypeName = "int")]
        [Index(@"PK_Language", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // ID (Primary key)

        [Column(@"Label", Order = 2, TypeName = "nvarchar")]
        [Index(@"AK_Language_Label", 1, IsUnique = true, IsClustered = false)]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(450)]
        [StringLength(450)]
        [Display(Name = "Label")]
        public string Label { get; set; } // Label (length: 450)

        [Column(@"Active", Order = 3, TypeName = "bit")]
        [Required]
        [Display(Name = "Active")]
        public bool Active { get; set; } // Active

        [Column(@"Disabled", Order = 4, TypeName = "bit")]
        [Required]
        [Display(Name = "Disabled")]
        public bool Disabled { get; set; } // Disabled

        // Reverse navigation

        /// <summary>
        /// Child ActivityLanguages where [ActivityLanguage].[LanguageID] point to this entity (FK_ActivityLanguage_Language_LanguageID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ActivityLanguage> ActivityLanguages { get; set; } // ActivityLanguage.FK_ActivityLanguage_Language_LanguageID

        public Language()
        {
            ActivityLanguages = new System.Collections.Generic.List<ActivityLanguage>();
        }
    }

}
// </auto-generated>
