// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace AmaFon.CrowdAct.Net.DataLayer.Contexts
{
    /// <summary>
    /// Defines the <see cref="CrowdActDbContextFactory" />
    /// </summary>
    public class CrowdActDbContextFactory : System.Data.Entity.Infrastructure.IDbContextFactory<CrowdActDbContext>
    {
        /// <summary>
        /// The Create
        /// </summary>
        /// <returns>The <see cref="CrowdActDbContext"/></returns>
        public CrowdActDbContext Create()
        {
            return new CrowdActDbContext();
        }
    }
}
// </auto-generated>