// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace AmaFon.CrowdAct.Net.DataLayer.Configurations
{
    using Entities;

    // Charity
    /// <summary>
    /// Defines the <see cref="CharityConfiguration" />
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class CharityConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Charity>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CharityConfiguration"/> class.
        /// </summary>
        public CharityConfiguration()
            : this("dbo")
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CharityConfiguration"/> class.
        /// </summary>
        /// <param name="schema">The schema<see cref="string"/></param>
        public CharityConfiguration(string schema)
        {
            Property(x => x.OrgName).IsOptional();
            Property(x => x.Description).IsOptional();
            Property(x => x.Picture).IsOptional();
            Property(x => x.Certificate).IsOptional();
            Property(x => x.Phone).IsOptional();
            Property(x => x.Website).IsOptional();
            Property(x => x.Siren).IsOptional();
            Property(x => x.Logo).IsOptional();
            Property(x => x.AddressId).IsOptional();
            Property(x => x.FieldId).IsOptional();
        }
    }
}
// </auto-generated>