// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace AmaFon.CrowdAct.Net.DataLayer.Configurations
{
    using Entities;

    // Requirement
    /// <summary>
    /// Defines the <see cref="RequirementConfiguration" />
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class RequirementConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Requirement>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RequirementConfiguration"/> class.
        /// </summary>
        public RequirementConfiguration()
            : this("dbo")
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RequirementConfiguration"/> class.
        /// </summary>
        /// <param name="schema">The schema<see cref="string"/></param>
        public RequirementConfiguration(string schema)
        {
            Property(x => x.Name).IsOptional();
            Property(x => x.ResourceTypeId).IsOptional();
            Property(x => x.RequirementStatusId).IsOptional();
        }
    }
}
// </auto-generated>