// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace AmaFon.CrowdAct.Net.DataLayer.Configurations
{
    using Entities;

    // ResourceType
    /// <summary>
    /// Defines the <see cref="ResourceTypeConfiguration" />
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class ResourceTypeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ResourceType>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceTypeConfiguration"/> class.
        /// </summary>
        public ResourceTypeConfiguration()
            : this("dbo")
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceTypeConfiguration"/> class.
        /// </summary>
        /// <param name="schema">The schema<see cref="string"/></param>
        public ResourceTypeConfiguration(string schema)
        {
        }
    }
}
// </auto-generated>