// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Amaris.Foundation.CrowdAct.NetDal.Interfaces
{
    using Entities;
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    public interface ICrowdActDbContext : System.IDisposable
    {
        System.Data.Entity.DbSet<AccountStatu> AccountStatus { get; set; } // AccountStatus
        System.Data.Entity.DbSet<Activity> Activities { get; set; } // Activity
        System.Data.Entity.DbSet<ActivityLanguage> ActivityLanguages { get; set; } // ActivityLanguage
        System.Data.Entity.DbSet<ActivityParticipant> ActivityParticipants { get; set; } // ActivityParticipant
        System.Data.Entity.DbSet<Address> Addresses { get; set; } // Address
        System.Data.Entity.DbSet<Category> Categories { get; set; } // Category
        System.Data.Entity.DbSet<Charity> Charities { get; set; } // Charity
        System.Data.Entity.DbSet<City> Cities { get; set; } // City
        System.Data.Entity.DbSet<Country> Countries { get; set; } // Country
        System.Data.Entity.DbSet<EfMigrationsHistory> EfMigrationsHistories { get; set; } // __EFMigrationsHistory
        System.Data.Entity.DbSet<Language> Languages { get; set; } // Language
        System.Data.Entity.DbSet<ParticipantStatu> ParticipantStatus { get; set; } // ParticipantStatus
        System.Data.Entity.DbSet<Requirement> Requirements { get; set; } // Requirement
        System.Data.Entity.DbSet<RequirementStatu> RequirementStatus { get; set; } // RequirementStatus
        System.Data.Entity.DbSet<ResourceType> ResourceTypes { get; set; } // ResourceType
        System.Data.Entity.DbSet<Skill> Skills { get; set; } // Skill
        System.Data.Entity.DbSet<Entities.Type> Types { get; set; } // Type
        System.Data.Entity.DbSet<User> Users { get; set; } // User

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }

}
// </auto-generated>
